// <auto-generated />
using System;
using Kaleido.Modules.Services.Grpc.Currencies.Common.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kaleido.Modules.Services.Grpc.Currencies.Migrations.Migrations
{
    [DbContext(typeof(CurrencyEntityDbContext))]
    [Migration("20241124115228_CurrencyEntity")]
    partial class CurrencyEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kaleido.Modules.Services.Grpc.Currencies.Common.Models.CurrencyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Symbol")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
